export const USER_LIST = [
  {
    id: 1,
    name: "John Doe",
    email: "M3oZu@example.com",
    last_message: "Hello, how are you?",
    is_read: false,
  },
  {
    id: 2,
    name: "Jane Doe",
    email: "l2Kl0@example.com",
    last_message: "I'm fine, thank you.",
    is_read: true,
  },
  {
    id: 3,
    name: "Viktor Klimov",
    email: "M3oZu@example.com",
    last_message: "That's great to hear!",
    is_read: false,
  },
  {
    id: 4,
    name: "John Doe",
    email: "M3oZu@example.com",
    last_message: "I'm glad to hear that.",
    is_read: true,
  },
  {
    id: 5,
    name: "Jane Doe",
    email: "l2Kl0@example.com",
    last_message: "That's great to hear!",
    is_read: false,
  },
  {
    id: 6,
    name: "Viktor Klimov",
    email: "M3oZu@example.com",
    last_message: "I'm glad to hear that.",
    is_read: true,
  },
  {
    id: 7,
    name: "John Doe",
    email: "M3oZu@example.com",
    last_message: "That's great to hear!",
    is_read: false,
  },
  {
    id: 8,
    name: "Jane Doe",
    email: "l2Kl0@example.com",
    last_message: "I'm glad to hear that.",
    is_read: true,
  },
  {
    id: 9,
    name: "Viktor Klimov",
    email: "M3oZu@example.com",
    last_message: "That's great to hear!",
    is_read: false,
  },
  {
    id: 10,
    name: "John Doe",
    email: "M3oZu@example.com",
    last_message: "I'm glad to hear that.",
    is_read: true,
  },
  {
    id: 11,
    name: "Jane Doe",
    email: "l2Kl0@example.com",
    last_message: "That's great to hear!",
    is_read: false,
  },
  {
    id: 12,
    name: "Faqih AI",
    last_message: "That's great to hear!",
    is_ai: true,
  },
];
